export const CART_ITEMS = 'CART_ITEMS';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const USER_REGISTER = 'USER_REGISTER'
export const SIGNIN = 'SIGNIN'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const SUBTRACT_QUANTITY = 'REMOVE_QUANTITY'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'